# Chapter 1. Ndarray

## 1.ndarray 的特性

### 多维性

In [2]:
import numpy as np
arr = np.array(5) #创建0维的ndarray数组

In [3]:
print(arr)
print('arr的维度',arr.ndim)#数组的维度 number of dimensions


5
arr的维度 0


In [4]:
arr = np.array([1,2,3])
print(arr)
print('arr的维度',arr.ndim)

[1 2 3]
arr的维度 1


In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('arr的维度',arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性

In [7]:
arr = np.array([1,'hello'])  #1变成了字符串,自动完成了数据转换
print(arr)
print('arr的维度',arr.ndim)

['1' 'hello']
arr的维度 1


In [8]:
arr = np.array([1,2.5])  # 1被加上了点变成了1.0 其中的0省略了
print(arr)

[1.  2.5]


# 2.ndarray 的属性

In [9]:
arr = np.array(1)  #1变成了字符串,自动完成了数据转换
print(arr)
print('数组的形状',arr.shape)

1
数组的形状 ()


In [10]:
arr = np.array([1,2,3])
print(arr)
print('arr的维度',arr.shape)

[1 2 3]
arr的维度 (3,)


In [13]:
arr = np.array([1,2,3])
print(arr)
print('arr的形状',arr.shape)
print('arr的维度',arr.ndim)
print('元素的个数',arr.size)
print('arr的维度',arr.dtype)

[1 2 3]
arr的形状 (3,)
arr的维度 1
元素的个数 3
arr的维度 int64


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('arr的转置',arr.T)

[[1 2 3]
 [4 5 6]]
arr的转置 [[1 4]
 [2 5]
 [3 6]]


# 3.ndarray的创建

In [14]:
#基础的创建方法
list1 = [1,2,3]
arr = np.array(list1, dtype=np.float64) #通知指定dtype强制指定类型
print(arr.ndim)
print(arr)


1
[1. 2. 3.]


In [16]:
#copy
arr1 = np.copy(arr) # 元素跟原始的数组相同,但不是同一个
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [20]:
#预定义形状
# 全0 全1 
# 全0
arr = np.zeros((2,3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [21]:
arr = np.zeros((200), dtype=int)
print(arr)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [22]:
arr = np.ones((5,8), dtype=int)
print(arr)


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [25]:
arr = np.empty((5,3), dtype=int)
print(arr)

[[                  0                   0 4601727903846100441]
 [4587820456862672466 4595745948572889240 4601727903846100441]
 [4596827656117413458 4600249548200259736 4601727903846100441]
 [4602288710223143708 4603108665757041778 4601727903846100441]
 [4605834855372154450 4604753147827630232 4601727903846100441]]


In [26]:
arr = np.full((3,4), 2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [28]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
