# Chapter 1. Ndarray

## 1.ndarray 的特性

### 多维性

In [2]:
import numpy as np
from numpy import ndarray
from pandas.conftest import unit2

arr = np.array(5) #创建0维的ndarray数组

In [3]:
print(arr)
print('arr的维度',arr.ndim)#数组的维度 number of dimensions


5
arr的维度 0


In [4]:
arr = np.array([1,2,3])
print(arr)
print('arr的维度',arr.ndim)

[1 2 3]
arr的维度 1


In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('arr的维度',arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性

In [7]:
arr = np.array([1,'hello'])  #1变成了字符串,自动完成了数据转换
print(arr)
print('arr的维度',arr.ndim)

['1' 'hello']
arr的维度 1


In [8]:
arr = np.array([1,2.5])  # 1被加上了点变成了1.0 其中的0省略了
print(arr)

[1.  2.5]


# 2.ndarray 的属性

In [9]:
arr = np.array(1)  #1变成了字符串,自动完成了数据转换
print(arr)
print('数组的形状',arr.shape)

1
数组的形状 ()


In [10]:
arr = np.array([1,2,3])
print(arr)
print('arr的维度',arr.shape)

[1 2 3]
arr的维度 (3,)


In [13]:
arr = np.array([1,2,3])
print(arr)
print('arr的形状',arr.shape)
print('arr的维度',arr.ndim)
print('元素的个数',arr.size)
print('arr的维度',arr.dtype)

[1 2 3]
arr的形状 (3,)
arr的维度 1
元素的个数 3
arr的维度 int64


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('arr的转置',arr.T)

[[1 2 3]
 [4 5 6]]
arr的转置 [[1 4]
 [2 5]
 [3 6]]


# 3.ndarray的创建

In [14]:
#基础的创建方法
list1 = [1,2,3]
arr = np.array(list1, dtype=np.float64) #通知指定dtype强制指定类型
print(arr.ndim)
print(arr)


1
[1. 2. 3.]


In [16]:
#copy
arr1 = np.copy(arr) # 元素跟原始的数组相同,但不是同一个
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [20]:
#预定义形状
# 全0 全1 
# 全0
arr = np.zeros((2,3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [21]:
arr = np.zeros((200), dtype=int)
print(arr)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [22]:
arr = np.ones((5,8), dtype=int)
print(arr)


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [25]:
arr = np.empty((5,3), dtype=int)
print(arr)

[[                  0                   0 4601727903846100441]
 [4587820456862672466 4595745948572889240 4601727903846100441]
 [4596827656117413458 4600249548200259736 4601727903846100441]
 [4602288710223143708 4603108665757041778 4601727903846100441]
 [4605834855372154450 4604753147827630232 4601727903846100441]]


In [26]:
arr = np.full((3,4), 2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [28]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [30]:
# 等差数列
arr = np.arange(1,10,1) # start,end,step
print(arr)
# 等差数列
arr = np.arange(2, 11, 2)  # start,end,step
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10]


In [32]:
# 等间隔序列
app = np.linspace(1,10,5) #要几个数
print(app)

[ 1.    3.25  5.5   7.75 10.  ]


In [36]:
app = np.linspace(0,100,5,dtype = int) #要几个数
print(app)
arr = np.arange(0, 101, 25)  # start,end,step
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [38]:
# 对数间隔数列
arr = np.logspace(0,4,2,base = 2) #base是底,一般默认是10
print(arr)

[ 1. 16.]


In [41]:
# 特殊矩阵
# 单位矩阵:主对角线上的数字为1,其他的数字为0
arr1 = np.eye(3,dtype=int)
arr2 = np.eye(3,4,dtype=int)
print(arr1)
print(arr2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [42]:
# 对角矩阵:主对角线上非0,其他的数字为0
arr = np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [44]:
# 随机数组的生成
# 生成0-1之间的随机浮点数
arr = np.random.rand(3,4) #括号里是形状
print(arr)

[[0.49451919 0.78121293 0.74082778 0.48707202]
 [0.62023444 0.7148053  0.4744466  0.54444536]
 [0.4924031  0.29141942 0.29430468 0.29820088]]


In [45]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3))
print(arr)



[[5.43395124 4.41217251 4.37605251]
 [5.22050898 3.01722514 4.04596398]]


In [47]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3,30,(2,3))
print(arr)


[[15  8 21]
 [19  7  6]]


In [49]:
# 生成随机数列(正态分布)
# 两边小中间大(基本是-3到3)
arr = (np.random.randn(2,3))
print(arr)

[[-1.22198398 -0.70313376  0.0376234 ]
 [-1.32652175  0.05596453  0.33854117]]


In [50]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


4.ndarray的数据类型

布尔类型 bool
整数类型 int uint
浮点数 float
复数 complex

In [52]:
arr = np.array([1,0,2,0], dtype = np.bool)
print(arr)

[ True False  True False]


In [54]:
arr = np.array([1,0,2,0], dtype = np.int8)
print(arr)

[1 0 2 0]


# 5 ndarray 索引切片



#一维数组的索引与切片

In [58]:
arr = np.random.randint(1,100,20)
print(arr)
print(arr[10]) #从0开始
print(arr[:]) #取的是全部
print(arr[2:5]) # 左包又不包
print(arr[(arr>10)&(arr<20)]) 打印出来大于10和小于20的元素

[83 79 11 34 86 18 41 83 43 61 85 31 37  9 49 20 49 96 54 11]
85
[83 79 11 34 86 18 41 83 43 61 85 31 37  9 49 20 49 96 54 11]
[11 34 86]
[11 18 11]


In [60]:
arr = np.random.randint(1,100,(4,8))
print(arr)

[[42 10 67 16 66 31 89 50]
 [41 12 70  1 59 87 38 69]
 [19 10 58 15 36 76 24 30]
 [61 98  3 20 87 46 86 85]]


In [65]:
print(arr[1,3])
print(arr[1,:])
print(arr[1,2:5])
print(arr[arr>50])
print(arr[2] [arr[2]>50])

1
[41 12 70  1 59 87 38 69]
[70  1 59]
[67 66 89 70 59 87 69 58 76 61 98 87 86 85]
[58 76]


5. ndarray 运算

In [67]:
#算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [70]:
c = [1,2,3]
d = [4,5,6]
print(c+d)
for i in range(len(c)):
    d[i] = c[i] + d[i]
print(d)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [74]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [75]:
print(a+3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [78]:
# 广播机制
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#矩阵运算
